### ISSUE TITLE
Logo improvements

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/pondersource.com#4]
The [current logo](https://pondersource.com/img/logo.png) has a number of issues:
* the o of 'ponder' should contain a brain, to symbolise thought
* on the mountains in the o of 'source', the source of a tiny swirling mountain river should be visible, to symbolise a source of water
* it's hard to put the logo into a circle (see for instance https://twitter.com/PonderSource/photo).

**Comment by 1984logo** [comment]
I'd like to propose the logo concepts below. 

**concept1** 
An update of the current logo.
![concept1](https://user-images.githubusercontent.com/84827852/122439489-a69a1980-cfd6-11eb-8458-abef0c3b7241.png)

**concept2**
 A new take on the same theme - focus on readability and usability.
![concept2](https://user-images.githubusercontent.com/84827852/122439494-a732b000-cfd6-11eb-8c37-7225af3fe013.png)

Hope this could help.

**Comment by michielbdejong** [comment]
Ha, thank you! In the meantime we actually paid someone through Fiverr to improve the logo, see https://pondersource.com/assets/logo.jpeg.

Your suggestions are nice though! We just printed 200 laptop stickers with the current improved logo, but we might want further logo changes in the future, if so, I'll keep you in mind!
